### ISSUE TITLE
bar.DecoratorEwmaUpdate doesn't show up in latest module

### ISSUE THREAD

**Issue by sedmo** [vbauerster/mpb#62]
I was able to resolve this by 
1. updating Go to 1.14
2. using v5 of code

BEFORE
![image](https://user-images.githubusercontent.com/23130212/79017636-d383ae80-7b3f-11ea-829c-4ac84f7eaa4f.png)

![image](https://user-images.githubusercontent.com/23130212/79017692-f2824080-7b3f-11ea-9382-a46a55e66920.png)

AFTER
![image](https://user-images.githubusercontent.com/23130212/79017665-e39b8e00-7b3f-11ea-8adc-27a231ecb5be.png)

![image](https://user-images.githubusercontent.com/23130212/79017678-ea2a0580-7b3f-11ea-8001-16371a2ef1d4.png)

**Comment by vbauerster** [comment]
I changed API slightly because `ewma` related api was confusing in v4 (#59, #46). Major version increase indicates incompatible API change as per [semver](https://semver.org). I assume you tried to use v5 api while importing v4, which of course won't work. As you already pointed out correct resolution, I'm closing this one.
