### ISSUE TITLE
multiple pbs start acting weirdly when the length of text bigger than terminal width

### ISSUE THREAD

**Issue by nitishgargiitd** [vbauerster/mpb#70]
```
textReset := "\033[0m"
textRed := "\033[4;31m"
failedState := textRed + pt.Error.Error() + textReset
return progressBars.AddBar(
	1,
	mpb.BarQueueAfter(replaceBar),
	mpb.BarStyle("     "),
	mpb.BarFillerClearOnComplete(),
	mpb.PrependDecorators(
		decor.Name("Bar Name", decor.WCSyncSpaceR),
		decor.Name(failedState, decor.WCSyncSpaceR),
	),
)
```

When pt.Error.Error() is big enough, it puts '...' at the end and makes the  coloring goes away for that line and it messes up next lines.

To reproduce, just simply run the https://github.com/vbauerster/mpb/blob/master/_examples/complex/main.go

and make the terminal width smaller than content length, hopefully it should reproduce the bug.

Platform: Mac OS
mpb version: https://github.com/vbauerster/mpb/commit/a55da8df10b6d8d8172eea63c25e65bf975806d6

**Comment by vbauerster** [comment]
It's expected behavior if there is no room to fit a bar in one line. I checked the example you're referring to and didn't see any "messes up next lines":
[![asciicast](https://asciinema.org/a/oRKcqCLkqPZUvoxot2dKg7xI0.svg)](https://asciinema.org/a/oRKcqCLkqPZUvoxot2dKg7xI0)

If you'd like to preserve coloring or affect default truncating behavior, you have to implement custom decorator as described [here](https://github.com/vbauerster/mpb/issues/55#issuecomment-627398955).

**Comment by nitishgargiitd** [comment]
sorry for the delayed response, I am going to try it tomorrow and let you know how the custom decorators solution goes.
